# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('present', models.NullBooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Student')),
            ],
        ),
    ]
