# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20171114_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=32, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.FloatField(verbose_name='cena'),
        ),
    ]
