# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 11:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('data_sent', models.DateTimeField(default=datetime.datetime(2017, 11, 16, 11, 48, 47, 605072))),
                ('fro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Student')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.SchoolSubject')),
            ],
        ),
    ]
