# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 13:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20171116_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Coś tam coś', max_length=100, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='message',
            name='data_sent',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 13, 53, 33, 707841)),
        ),
        migrations.AddField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(to='exercises.Book'),
        ),
    ]
