# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0003_auto_20171023_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128, null=True)),
                ('content', models.TextField()),
                ('date_added', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'w trakcie pisania'), (2, 'czeka na akceptację redaktora'), (3, 'opublikowany')])),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
            ],
        ),
    ]
