# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0005_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
