# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0007_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_1.Product'),
            preserve_default=False,
        ),
    ]
