# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0008_opinion_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('value_in_percent', models.FloatField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_1.Product')),
            ],
        ),
    ]
