# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_1', '0009_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(to='django_1.Product')),
            ],
        ),
    ]
